/**
 * K6 Load Testing Script for Phase III AI-Powered Chatbot
 *
 * Generated by /sp.test-suite
 *
 * This script tests the chatbot API endpoints under various load conditions.
 *
 * Usage:
 *   k6 run k6_script.js
 *   k6 run --vus 10 --duration 30s k6_script.js
 */

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Rate, Trend } from 'k6/metrics';

// Custom metrics
const errorRate = new Rate('errors');
const chatResponseTime = new Trend('chat_response_time');

// Test configuration
export const options = {
  stages: [
    { duration: '30s', target: 10 },  // Ramp up to 10 users
    { duration: '1m', target: 50 },   // Ramp up to 50 users
    { duration: '2m', target: 50 },   // Stay at 50 users
    { duration: '30s', target: 100 }, // Spike to 100 users
    { duration: '1m', target: 100 },  // Stay at 100 users
    { duration: '30s', target: 0 },   // Ramp down
  ],
  thresholds: {
    http_req_duration: ['p(95)<2000'], // 95% of requests under 2s
    http_req_failed: ['rate<0.05'],    // Error rate < 5%
    errors: ['rate<0.1'],              // Custom error rate < 10%
  },
};

// Base URL (override with K6_BASE_URL env var)
const BASE_URL = __ENV.K6_BASE_URL || 'http://localhost:8000';

// Sample data
const taskTitles = [
  'Buy groceries',
  'Call dentist',
  'Finish project report',
  'Exercise',
  'Read a book',
];

const chatMessages = {
  create: [
    'Add a task to buy groceries',
    'I need to remember to call mom',
    'Create a task: Finish project report',
  ],
  list: [
    'Show me all my tasks',
    'What tasks do I have?',
    'List my pending tasks',
  ],
  complete: [
    'Mark task 1 as complete',
    'I finished task 2',
    'Complete the groceries task',
  ],
  update: [
    'Change task 1 to Buy milk and eggs',
    'Update task 2 description',
  ],
  delete: [
    'Delete task 3',
    'Remove the meeting task',
  ],
};

export default function () {
  const userId = `k6_user_${__VU}`; // Virtual User ID
  let conversationId = null;

  // Test: Create task via chat
  testCreateTask(userId, conversationId);
  sleep(1);

  // Test: List tasks via chat
  testListTasks(userId, conversationId);
  sleep(1);

  // Test: Complete task via chat
  testCompleteTask(userId, conversationId);
  sleep(1);

  // Test: Update task via chat
  testUpdateTask(userId, conversationId);
  sleep(1);

  // Test: Delete task via chat
  testDeleteTask(userId, conversationId);
  sleep(1);
}

function testCreateTask(userId, conversationId) {
  const message = chatMessages.create[Math.floor(Math.random() * chatMessages.create.length)];

  const payload = JSON.stringify({
    conversation_id: conversationId,
    message: message,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer test_token_${userId}`,
    },
    tags: { name: 'ChatCreateTask' },
  };

  const response = http.post(`${BASE_URL}/api/${userId}/chat`, payload, params);

  const success = check(response, {
    'create task: status 200': (r) => r.status === 200,
    'create task: has response': (r) => r.json('response') !== undefined,
    'create task: has conversation_id': (r) => r.json('conversation_id') !== undefined,
  });

  errorRate.add(!success);
  chatResponseTime.add(response.timings.duration);

  if (success && response.json('conversation_id')) {
    conversationId = response.json('conversation_id');
  }
}

function testListTasks(userId, conversationId) {
  const message = chatMessages.list[Math.floor(Math.random() * chatMessages.list.length)];

  const payload = JSON.stringify({
    conversation_id: conversationId,
    message: message,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer test_token_${userId}`,
    },
    tags: { name: 'ChatListTasks' },
  };

  const response = http.post(`${BASE_URL}/api/${userId}/chat`, payload, params);

  const success = check(response, {
    'list tasks: status 200': (r) => r.status === 200,
    'list tasks: has response': (r) => r.json('response') !== undefined,
  });

  errorRate.add(!success);
  chatResponseTime.add(response.timings.duration);
}

function testCompleteTask(userId, conversationId) {
  const message = chatMessages.complete[Math.floor(Math.random() * chatMessages.complete.length)];

  const payload = JSON.stringify({
    conversation_id: conversationId,
    message: message,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer test_token_${userId}`,
    },
    tags: { name: 'ChatCompleteTask' },
  };

  const response = http.post(`${BASE_URL}/api/${userId}/chat`, payload, params);

  const success = check(response, {
    'complete task: status 200': (r) => r.status === 200,
  });

  errorRate.add(!success);
  chatResponseTime.add(response.timings.duration);
}

function testUpdateTask(userId, conversationId) {
  const message = chatMessages.update[Math.floor(Math.random() * chatMessages.update.length)];

  const payload = JSON.stringify({
    conversation_id: conversationId,
    message: message,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer test_token_${userId}`,
    },
    tags: { name: 'ChatUpdateTask' },
  };

  const response = http.post(`${BASE_URL}/api/${userId}/chat`, payload, params);

  const success = check(response, {
    'update task: status 200': (r) => r.status === 200,
  });

  errorRate.add(!success);
  chatResponseTime.add(response.timings.duration);
}

function testDeleteTask(userId, conversationId) {
  const message = chatMessages.delete[Math.floor(Math.random() * chatMessages.delete.length)];

  const payload = JSON.stringify({
    conversation_id: conversationId,
    message: message,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer test_token_${userId}`,
    },
    tags: { name: 'ChatDeleteTask' },
  };

  const response = http.post(`${BASE_URL}/api/${userId}/chat`, payload, params);

  const success = check(response, {
    'delete task: status 200': (r) => r.status === 200,
  });

  errorRate.add(!success);
  chatResponseTime.add(response.timings.duration);
}

export function handleSummary(data) {
  return {
    'stdout': textSummary(data, { indent: ' ', enableColors: true }),
    'summary.json': JSON.stringify(data),
  };
}
