"""Load testing scenarios for Phase III AI-Powered Chatbot.

Generated by /sp.test-suite

This file defines load testing scenarios using Locust to simulate
realistic user behavior and measure system performance under load.

Usage:
    locust -f locustfile.py --host=http://localhost:8000
    # Open browser to http://localhost:8089
"""

from locust import HttpUser, task, between, events
import random
import json
import logging

logger = logging.getLogger(__name__)


class ChatbotUser(HttpUser):
    """Simulated user for load testing the AI chatbot.

    This user simulates realistic interaction patterns:
    - Creates conversations
    - Sends chat messages
    - Performs task operations via chat
    - Maintains conversation context
    """

    wait_time = between(2, 5)  # Wait 2-5 seconds between requests

    def on_start(self):
        """Initialize user session with authentication."""
        # For testing, use a test user token
        # In production, implement proper authentication
        self.user_id = f"load_test_user_{random.randint(1, 1000)}"
        self.conversation_id = None
        self.tasks_created = []

        # Mock auth token (replace with real auth in production)
        self.headers = {
            "Authorization": f"Bearer test_token_{self.user_id}",
            "Content-Type": "application/json"
        }

        logger.info(f"User {self.user_id} started")

    @task(5)
    def chat_create_task(self):
        """Simulate creating a task via chat (most common operation)."""
        task_titles = [
            "Buy groceries",
            "Call dentist",
            "Finish project report",
            "Exercise for 30 minutes",
            "Read a book",
            "Clean the house",
            "Water the plants",
            "Pay bills"
        ]

        message = f"Add a task to {random.choice(task_titles)}"

        with self.client.post(
            f"/api/{self.user_id}/chat",
            json={
                "conversation_id": self.conversation_id,
                "message": message
            },
            headers=self.headers,
            catch_response=True,
            name="/api/chat [CREATE TASK]"
        ) as response:
            if response.status_code == 200:
                data = response.json()
                if not self.conversation_id:
                    self.conversation_id = data.get("conversation_id")
                response.success()
            else:
                response.failure(f"Failed to create task: {response.status_code}")

    @task(3)
    def chat_list_tasks(self):
        """Simulate listing tasks via chat."""
        messages = [
            "Show me all my tasks",
            "What tasks do I have?",
            "List my pending tasks",
            "Show me completed tasks"
        ]

        with self.client.post(
            f"/api/{self.user_id}/chat",
            json={
                "conversation_id": self.conversation_id,
                "message": random.choice(messages)
            },
            headers=self.headers,
            catch_response=True,
            name="/api/chat [LIST TASKS]"
        ) as response:
            if response.status_code == 200:
                data = response.json()
                if not self.conversation_id:
                    self.conversation_id = data.get("conversation_id")
                response.success()
            else:
                response.failure(f"Failed to list tasks: {response.status_code}")

    @task(2)
    def chat_complete_task(self):
        """Simulate completing a task via chat."""
        messages = [
            "Mark task 1 as complete",
            "I finished task 2",
            "Complete task 3",
            "Task 4 is done"
        ]

        with self.client.post(
            f"/api/{self.user_id}/chat",
            json={
                "conversation_id": self.conversation_id,
                "message": random.choice(messages)
            },
            headers=self.headers,
            catch_response=True,
            name="/api/chat [COMPLETE TASK]"
        ) as response:
            if response.status_code == 200:
                data = response.json()
                if not self.conversation_id:
                    self.conversation_id = data.get("conversation_id")
                response.success()
            else:
                response.failure(f"Failed to complete task: {response.status_code}")

    @task(1)
    def chat_update_task(self):
        """Simulate updating a task via chat."""
        messages = [
            "Change task 1 to 'Buy milk and eggs'",
            "Update task 2 description",
            "Rename task 3"
        ]

        with self.client.post(
            f"/api/{self.user_id}/chat",
            json={
                "conversation_id": self.conversation_id,
                "message": random.choice(messages)
            },
            headers=self.headers,
            catch_response=True,
            name="/api/chat [UPDATE TASK]"
        ) as response:
            if response.status_code == 200:
                response.success()
            else:
                response.failure(f"Failed to update task: {response.status_code}")

    @task(1)
    def chat_delete_task(self):
        """Simulate deleting a task via chat."""
        messages = [
            "Delete task 5",
            "Remove task 6",
            "Get rid of task 7"
        ]

        with self.client.post(
            f"/api/{self.user_id}/chat",
            json={
                "conversation_id": self.conversation_id,
                "message": random.choice(messages)
            },
            headers=self.headers,
            catch_response=True,
            name="/api/chat [DELETE TASK]"
        ) as response:
            if response.status_code == 200:
                response.success()
            else:
                response.failure(f"Failed to delete task: {response.status_code}")

    @task(1)
    def chat_help(self):
        """Simulate asking for help."""
        messages = [
            "What can you do?",
            "Help",
            "How do I create a task?",
            "Tell me about your features"
        ]

        with self.client.post(
            f"/api/{self.user_id}/chat",
            json={
                "conversation_id": self.conversation_id,
                "message": random.choice(messages)
            },
            headers=self.headers,
            catch_response=True,
            name="/api/chat [HELP]"
        ) as response:
            if response.status_code == 200:
                response.success()
            else:
                response.failure(f"Failed to get help: {response.status_code}")

    def on_stop(self):
        """Cleanup when user session ends."""
        logger.info(f"User {self.user_id} stopped")


class StressTestUser(HttpUser):
    """Stress test user with rapid requests."""

    wait_time = between(0.1, 0.5)  # Very short wait time

    def on_start(self):
        self.user_id = f"stress_user_{random.randint(1, 10000)}"
        self.conversation_id = None
        self.headers = {
            "Authorization": f"Bearer test_token_{self.user_id}",
            "Content-Type": "application/json"
        }

    @task
    def rapid_chat(self):
        """Rapid-fire chat messages for stress testing."""
        messages = [f"Test message {i}" for i in range(10)]

        self.client.post(
            f"/api/{self.user_id}/chat",
            json={
                "conversation_id": self.conversation_id,
                "message": random.choice(messages)
            },
            headers=self.headers,
            name="/api/chat [STRESS]"
        )


@events.test_start.add_listener
def on_test_start(environment, **kwargs):
    """Log when load test starts."""
    logger.info("=" * 50)
    logger.info("Load Test Starting")
    logger.info(f"Host: {environment.host}")
    logger.info("=" * 50)


@events.test_stop.add_listener
def on_test_stop(environment, **kwargs):
    """Log test results when load test stops."""
    logger.info("=" * 50)
    logger.info("Load Test Complete")
    logger.info(f"Total requests: {environment.stats.total.num_requests}")
    logger.info(f"Total failures: {environment.stats.total.num_failures}")
    logger.info(f"Average response time: {environment.stats.total.avg_response_time:.2f}ms")
    logger.info(f"Requests per second: {environment.stats.total.total_rps:.2f}")
    logger.info("=" * 50)
