apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "YOUR-CLUSTER.cloud.redpanda.com:9092"
    - name: authType
      value: "password"
    - name: saslUsername
      value: ""  # Set via secret
    - name: saslPassword
      value: ""  # Set via secret
    - name: saslMechanism
      value: "SCRAM-SHA-256"
    - name: initialOffset
      value: "oldest"
    - name: consumerGroup
      value: "todo-service"
